name: Docker Image CI

on:
  release:
    types: [published]
jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          registry: ghcr.io
      -
        name: Build and Push arm64
        uses: docker/build-push-action@v6
        with:
          context: .
          tags:
            ghcr.io/tech1ndex/qrcode-generator:${{ github.event.release.tag_name }}-arm64
          platforms: linux/arm64
          push: true
      -
         name: Build and Push amd64
         uses: docker/build-push-action@v6
         with:
          context: .
          tags: ghcr.io/tech1ndex/qrcode-generator:${{ github.event.release.tag_name }}-amd64
          platforms: linux/amd64
          push: true
      -
        name: Create and Push manifest
        run: |
          docker buildx imagetools create -t ghcr.io/tech1ndex/qrcode-generator:latest \
            ghcr.io/tech1ndex/qrcode-generator:${{ github.event.release.tag_name }}-amd64 \
            ghcr.io/tech1ndex/qrcode-generator:${{ github.event.release.tag_name }}-arm64